version: "3"

services:
  web-app:
    build:
      context: ./webapp/
      dockerfile: Dockerfile.prod
    container_name: predict-growth-stop-web-app
    volumes:
      - webapp-build:/webapp/build
    environment:
      BROWSER: "none"

  server:
    build:
      context: ./server/
      dockerfile: Dockerfile.prod
    container_name: predict-growth-stop-server
    environment:
      NODE_ENV: "production"
    volumes:
      - webapp-build:/server/lib/build
    ports:
      - 3050:3050

volumes:
  webapp-build: