version: "3"

services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile.prod
    container_name: predict-growth-stop-server
    environment:
      NODE_ENV: "production"
    volumes:
      - ./webapp/build:/server/lib/build
    ports:
      - 3050:3050

volumes:
  webapp-build: