const GRID_BORDER_RADIUS = "6px";
const GRID_HEIGHT = "120px";
const GRID_HEIGHT_MOBILE = "40px";
const DATA_WIDTH = "62px";
const LEGEND_WIDTH = "120px";
const LEGEND_WIDTH_MOBILE = "80px";
const DATA_WIDTH_MOBILE = LEGEND_WIDTH_MOBILE;
const ADD_DATA_HEIGHT = "116px";
const ADD_DATA_WIDTH = DATA_WIDTH;
const ADD_DATA_WIDTH_MOBILE = "244PX";

export {
  ADD_DATA_HEIGHT,
  ADD_DATA_WIDTH,
  ADD_DATA_WIDTH_MOBILE,
  GRID_BORDER_RADIUS,
  GRID_HEIGHT,
  GRID_HEIGHT_MOBILE,
  DATA_WIDTH,
  DATA_WIDTH_MOBILE,
  LEGEND_WIDTH,
  LEGEND_WIDTH_MOBILE,
};
